version: "2.4"

services:
  node1:
    container_name: node1
    build: ./node1
    ports:
    - "5001:5000"
  node2:
    container_name: node2
    build: ./node2
    ports:
    - "5002:5000"
  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    depends_on:
      - node1
      - node2
