version: "2.4"

services:
  node1:
    container_name: node1
    build: ./node1
    expose:
    - '5001'
  node2:
    container_name: node2
    build: ./node2
    expose:
    - '5002'
  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    depends_on:
      - node1
      - node2
